version: "3.7"
services:
  db:
    image: mysql:8.0.19
    container_name: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060
  backend:
    image: garora123/nginx-flask-mysql # Ref: https://github.com/docker/awesome-compose
    container_name: app
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: .
      Dockerfile: nginx/Dockerfile
    restart: always
    volumes:
      - nginx/certs:/etc/nginx/certs
    ports:
      - 443:80
    depends_on:
      - backend
    networks:
      - frontnet
volumes:
  - db-data:
secrets:
  db-password:
    file: db/password # ideally secret management system like vault should be used
networks:
  backnet:
    ipam:
      driver: default
      config:
        - subnet: <subnet of the container>
  frontnet:
    driver: macvlan
    driver_opts:
      parent: br0
    ipam:
      driver: default
      config:
        - gateway: <gw of the docker host>
          subnet: <subnet of the docker host>
